from django.urls import path
from . import views

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('keys/active/', views.ActiveKeysList.as_view(), name='keys'),
    path('keys/inactive/', views.InactiveKeysList.as_view(), name='keys_inactive'),
    path('keys/pending/', views.PendingKeysList.as_view(), name='keys_pending'),
    path('keys/action/activate/<slug:hash>/', views.ActivateKey, name='activate_key'),
    path('keys/action/deactivate/<slug:hash>/', views.DeactivateKey, name='deactivate_key'),
    path('keys/action/remove/<slug:hash>/', views.RemoveKey, name='remove_key'),
    path('keys/details/<slug:hash>', views.KeyDetails.as_view(), name='key_details'),
    path('keys/new/', views.NewKey.as_view(), name='new_key'),
    path('key/modify/<slug:hash>', views.ModifyKey.as_view(), name='modify_key'),
    path('key/search/', views.KeySearch, name='key_search'),
    path('transactions/', views.TransactionsList.as_view(), name='transactions'),
    path('transactions/advanced_search/', views.AdvancedSearch.as_view(), name='advanced_search'),
    path('transactions/<slug:hash>', views.TransactionDetail.as_view(), name='transaction_details'),
    path('remote_register/<slug:value>', views.ChangeRemoteRegisterStatus, name='remote_register'),
    path('ids/search/', views.IdSearch.as_view(), name='id_search'),
    path('ids/details/<slug:id>', views.IdDetails.as_view(), name='id_details'),
    path('config/products/', views.ProductList.as_view(), name='config_products'),
    path('config/products/new', views.NewProduct.as_view(), name='new_product'),
    path('config/products/details/<slug:code>', views.ProductDetails.as_view(), name='product_details'),
    path('config/products/modify/<slug:code>', views.ModifyProduct.as_view(), name='modify_product'),
    path('config/products/remove/<slug:code>', views.RemoveProduct, name='remove_product'),
    path('config/origins/', views.OriginList.as_view(), name='config_origins'),
    path('config/origins/new', views.NewOrigin.as_view(), name='new_origin'),
    path('config/origins/details/<slug:code>', views.OriginDetails.as_view(), name='origin_details'),
    path('config/origins/modify/<slug:code>', views.ModifyOrigin.as_view(), name='modify_origin'),
    path('config/origins/remove/<slug:code>', views.RemoveOrigin, name='remove_origin'),
    path('config/destinations/', views.DestinationList.as_view(), name='config_destinations'),
    path('config/destinations/new', views.NewDestination.as_view(), name='new_destination'),
    path('config/destinations/details/<slug:code>', views.DestinationDetails.as_view(), name='destination_details'),
    path('config/destinations/modify/<slug:code>', views.ModifyDestination.as_view(), name='modify_destination'),
    path('config/destinations/remove/<slug:code>', views.RemoveDestination, name='remove_destination'),
]